exports.BASE_CURRENCY_CODE = 'USD';
exports.RATES_HISTORY_TIMEFRAMES = {
    MONTH: 'MONTH',
    THREE_MONTHS: 'THREE_MONTHS',
    SIX_MONTHS: 'SIX_MONTHS',
    TWELVE_MONTHS: 'TWELVE_MONTHS',
}
exports.TIMEFRAME_TO_DAY_INTERVAL_MAP = {
    [exports.RATES_HISTORY_TIMEFRAMES.MONTH]: 1,
    [exports.RATES_HISTORY_TIMEFRAMES.THREE_MONTHS]: 3,
    [exports.RATES_HISTORY_TIMEFRAMES.SIX_MONTHS]: 6,
    [exports.RATES_HISTORY_TIMEFRAMES.TWELVE_MONTHS]: 12,
}