export const CURRENT_CURRENCIES_CODES = ['USD', 'EUR', 'GBP', 'CAD', 'MXN', 'JPY'];
export const BASE_CURRENCY_CODE = 'USD';
export const MAX_LATEST_CURRENCIES_DISPLAYED = 5;
export const DEFAULT_AMOUNT = (1000).toFixed(2);

export const HISTORY_TIMEFRAMES = {
    MONTH: 'MONTH',
    THREE_MONTHS: 'THREE_MONTHS',
    SIX_MONTHS: 'SIX_MONTHS',
    TWELVE_MONTHS: 'TWELVE_MONTHS',
};
